version: "3.8"
services:
  chromadb:
    image: chromadb/chroma:latest
    # container_name: chroma-server 
    volumes:
      - ./chromadb:/data/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/data/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - 8000:8000

#    networks:
#      - net
#networks:
#  net:
#    driver: bridge