FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9
COPY ./py_lib/* /py_lib/
COPY ./app/* /app/
COPY ./config/* /config/
COPY ./knowledge/* /knowledge/
RUN pip install --upgrade pip && pip cache purge
RUN pip install -r /py_lib/requirement.txt && pip cache purge
EXPOSE 80