apiVersion: v1
kind: ConfigMap
metadata:
  name: si-backend-configmap-dev
data:
  MONGO_URI: "mongodb+srv://si-admin:SI-admin1234@si-cluster.abw4huo.mongodb.net/?retryWrites=true&w=majority&appName=si-cluster"
  MONGO_DB_NAME: "system_intelligence_db"
  MONGO_PORT: "27017"
  DEBUG: "true"
  AZURE_CLIENT_ID: "7f35cd86-e3e8-4d70-833a-8961f6dc9d82"
  AZURE_TENANT_ID: "0d8d044e-89bf-4722-9556-04163b0c4348"
  AZURE_VAULT_URL: "https://productsupport-kv.vault.azure.net/"
  AZURE_OPENAI_ENDPOINT: "https://productsupportopenai.openai.azure.com/"
  AZURE_OPENAI_API_VERSION: "2024-02-01"
  AZURE_DEPLOYMENT_NAME: "system-intelligence-gpt-35-turbo-instruct"
  OPENAI_MAX_TOKENS: "300"
  OPENAI_TEMPERATURE: "0.5"
  LLAMA_MAX_TOKENS: "128"
  LLAMA_TEMPERATURE: "0.58"
  LLAMA_TOP_P: "0.1"
  LLAMA_BEST_OF: "1"
  LLAMA_PRESENCE_PENALITY: "0"
  LLAMA_ENDPOINT: "https://Meta-Llama-3-70B-Instruct-ztbdq-serverless.eastus2.inference.ai.azure.com/v1/chat/completions"
  LLAMA_MODEL_LOCAL_PATH: "../model/llama-2-7b-chat.Q5_0.gguf"
  LLAMA_MODEL_PATH: "/model/llama-2-7b-chat.Q5_0.gguf"
  CHROMA_HOST: "productsupportchromadb.si-app.svc.cluster.local"
  CHROMA_PORT: "8000"
  CHROMA_DB_PATH: "../chromadb"
  CHROMA_DB_NAME: "system_intelligence_chromadb"
  CHROMA_DB_COLLECTION_NAME: "system_intelligence_collection"
  CHROMA_DB_READER_EMBED_MODEL: "all-mpnet-base-v2"
  CHROMA_DB_WRITER_EMBED_MODEL: "all-MiniLM-L6-v2"
  KAFKA_HOST: "kafka"
  KAFKA_PORT: "9092"
  KAFKA_ACKS: "all"
  KAFKA_RETRIES: "3"
  KAFKA_LINGER: "3"
  KAFKA_TOPIC_NAME: "enrichment"
