apiVersion: apps/v1
kind: Deployment
metadata:
  name: systemintelligencebackendapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: systemintelligencebackendapp
  template:
    metadata:
      labels:
        app: systemintelligencebackendapp
    spec:
      containers:
      - name: systemintelligencebackendapp
        image: issappacr.azurecr.io/si/system-intelligence-backend:2.2.6
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "1Gi" 
            cpu: "500m"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: si-backend-configmap-dev
        - secretRef:
            name: si-backend-secret-dev
---
apiVersion: v1
kind: Service
metadata:
  name: systemintelligencebackendapp
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: systemintelligencebackendapp