apiVersion: apps/v1
kind: Deployment
metadata:
  name: productsupportchromadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productsupportchromadb
  template:
    metadata:
      labels:
        app: productsupportchromadb
    spec:
      containers:
      - name: productsupportchromadb
        image: chromadb/chroma:latest
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "500Mi" 
            cpu: "250m"
        ports:
        - containerPort: 8000
        env:
        - name: IS_PERSISTENT
          value: "TRUE"
        - name: PERSIST_DIRECTORY
          value: "/data/chroma"
        - name: ANONYMIZED_TELEMETRY
          value: "FALSE"
---
apiVersion: v1
kind: Service
metadata:
  name: productsupportchromadb
spec:
  type: ClusterIP
  ports:
  - port: 8000
  selector:
    app: productsupportchromadb