apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  serviceName: "kafka"
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
      - name: init-permissions
        image: busybox
        command:
          - sh
          - -c
          - |
            rm -rf /var/lib/kafka/data/lost+found
            chown -R 1000:1000 /var/lib/kafka/data
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.5.0
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper.si-app-dev.svc.cluster.local:2181  # FQDN for Zookeeper
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka.si-app-dev.svc.cluster.local:9092  # FQDN for Kafka
        - name: KAFKA_LOG_DIRS
          value: /var/lib/kafka/data
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS
          value: "600000"
        - name: KAFKA_LOG4J_LOGGERS
          value: "kafka.controller=DEBUG,kafka.producer.async.DefaultEventHandler=DEBUG,state.change.logger=DEBUG"
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: managed-premium-rw
      resources:
        requests:
          storage: 4Gi



---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      name: kafka
  clusterIP: None  # Headless service for stateful communication
  selector:
    app: kafka
