apiVersion: v1
kind: ConfigMap
metadata:
  name: si-kafka-consumer-configmap-dev
data:
  MONGO_URI: "mongodb+srv://si-admin:SI-admin1234@si-cluster.abw4huo.mongodb.net/?retryWrites=true&w=majority&appName=si-cluster"
  MONGO_DB_NAME: "system_intelligence_db"
  MONGO_PORT: "27017"
  DEBUG: "true"
  CHROMA_HOST: "productsupportchromadb.si-app.svc.cluster.local"
  CHROMA_PORT: "8000"
  CHROMA_DB_PATH: "../chromadb"
  CHROMA_DB_NAME: "system_intelligence_chromadb"
  CHROMA_DB_COLLECTION_NAME: "system_intelligence_collection"
  CHROMA_DB_READER_EMBED_MODEL: "all-mpnet-base-v2"
  CHROMA_DB_WRITER_EMBED_MODEL: "all-MiniLM-L6-v2"
  KAFKA_HOST: "kafka"
  KAFKA_PORT: "9092"
  GROUP_ID: "si-group"
  AUTO_OFFSET_RESET: "earliest"
  SESSION_TIMEOUT: "6000"
  MAX_POLL_INTERVAL: "300000"
  MESSAGE_MAX_BYTES: "1000000000"
  KAFKA_TOPIC_NAME: "enrichment"
  NUM_PARTITIONS: "1"
  REPLICATION_FACTOR: "1"