apiVersion: apps/v1
kind: Deployment
metadata:
  name: systemintelligencebackendapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: systemintelligencebackendapp
  template:
    metadata:
      labels:
        app: systemintelligencebackendapp
    spec:
      containers:
      - name: systemintelligencebackendapp
        image: issappacr.azurecr.io/si/system-intelligence-backend:2.0.7
        resources:
          requests:
            memory: "6Gi"
            cpu: "500m"
          limits:
            memory: "6Gi" 
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: CHROMA_HOST
          value: "productsupportchromadb.si-app.svc.cluster.local"
        - name: CHROMA_PORT
          value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: systemintelligencebackendapp
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: systemintelligencebackendapp