apiVersion: apps/v1
kind: Deployment
metadata:
  name: productsupportbackendapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productsupportbackendapp
  template:
    metadata:
      labels:
        app: productsupportbackendapp
    spec:
      containers:
      - name: productsupportbackendapp
        image: myil/productsupportai-backend:1.0.0
        ports:
        - containerPort: 80