apiVersion: apps/v1
kind: Deployment
metadata:
  name: systemintelligencebackendapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: systemintelligencebackendapp
  template:
    metadata:
      labels:
        app: systemintelligencebackendapp
    spec:
      containers:
      - name: systemintelligencebackendapp
        image: poornagollakoti/system_intelligence:1.0.0
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi" 
            cpu: "1"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: si-backend-configmap-stage
      # imagePullSecrets:
      # - name: siregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: systemintelligencebackendapp
spec:
  type: NodePort
  selector:
    app: systemintelligencebackendapp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002