apiVersion: v1
kind: Service
metadata:
  name: productsupportbackendapp-service
  labels:
      name: productsupportbackendapp-service
      provider: Heartsource
spec:
  selector:
    app: productsupportbackendapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 30080
      name: http
    - port: 443
      nodePort: 30443
      name: https
  type: NodePort