version: "3.8"

services:
  react-app:
    build:
      context: .
      args:
        ENV_FILE: .env.development
    image: issappacr.azurecr.io/si/system-intelligence-ui:0.1.4
    ports:
      - "80:80"
